version: "3.8"

services:
  # =============================================================================
  # MICROSERVICIO DE RECLAMOS E INCIDENTES
  # =============================================================================
  vg-ms-claims-incidents:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    image: vallegrande/vg-ms-claims-incidents:latest
    container_name: vg-ms-claims-inc
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      # CONFIGURACIÓN BÁSICA
      - SPRING_PROFILES_ACTIVE=dev
      - NOMBRE_MICROSERVICIO=claims-incidents
      - SERVER_PORT=8080

      # JWT CONFIGURATION - These will be used if your application.yml points to them
      - JWT_SECRET=dev-secret-key-for-local-development-only  # Replace with a strong, generated key for production
      - JWT_EXPIRATION=3600000
      - JWT_REFRESH_EXPIRATION=86400000
      - JWT_ISSUER=vallegrande-claims-incidents

      # INFORMACIÓN DE LA APLICACIÓN
      - APP_NAME=Claims Incidents Microservice
      - APP_DESCRIPTION=API para la gestión de reclamos e incidentes
      - APP_VERSION=1.0.0
      - APP_CONTACT_NAME=Santiago

      # JAVA OPTIONS
      - JAVA_OPTS=-Xmx512m -Xms256m
    volumes:
      - ./logs:/app/logs
    networks:
      - jass-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

# =============================================================================
# NETWORKS
# =============================================================================
networks:
  jass-network:
    driver: bridge
    name: jass-digital-network 